template = "https://github.com/giellalt/template-lang-und"
rev_id = 345
template_sha = "f04ff6c72fd325cdfed0bbaee815bd2f43d847a7"

[replacements]
__GLOTTOLOG_ID__ = "stan1293"
__REPO__ = "lang-eng"
__UND2C__ = "en"
__UNDEFINED__ = "English"
__UND__ = "eng"
