template = "https://github.com/giellalt/template-lang-und"
rev_id = 316
template_sha = "4ab8b281df40078b127cd15db6e63507b51b4424"

[replacements]
__GLOTTOLOG_ID__ = "stan1293"
__REPO__ = "lang-eng"
__UND2C__ = "en"
__UNDEFINED__ = "English"
__UND__ = "eng"
