template = "https://github.com/giellalt/template-lang-und"
rev_id = 313
template_sha = "818c033010c3b7b906621cdeca79061f50bd93ed"

[replacements]
__GLOTTOLOG_ID__ = "stan1293"
__REPO__ = "lang-eng"
__UND2C__ = "en"
__UNDEFINED__ = "English"
__UND__ = "eng"
